### ISSUE TITLE
for...in loops cause errors

### ISSUE THREAD

**Issue by istvank** [y-js/y-map#1]
https://github.com/y-js/y-map/blob/master/src/Map.js#L22
Seems to be the same issue as in
https://github.com/y-js/yjs/issues/46

**Comment by dmonad** [comment]
Dooone

**Comment by istvank** [comment]
sure? :)

**Comment by dmonad** [comment]
:sweat_smile: Sorry. Now it's really done

**Comment by istvank** [comment]
Confirming, it works now! :+1: Cool!

**Comment by dmonad** [comment]
:sparkles: :sparkles: :sparkles:
