### ISSUE TITLE
unobserveDeep calls addEventListener instead of removeEventListener

### ISSUE THREAD

**Issue by hcsalis** [y-js/y-map#10]
Hi @dmonad, 
Came across this while checking out the source code. I guess this is a simple copy paste error. Same issue is also present in y-array. But I am not opening another issue there. 

Thanks for your hard work on this awesome library!

[y-map unobserveDeep](https://github.com/y-js/y-map/blob/master/src/Map.js#L219)

[y-array unobserveDeep](https://github.com/y-js/y-array/blob/master/src/Array.js#L291)

**Comment by dmonad** [comment]
Uhh.. this is bad. Thanks a lot for checking my code :) I would have never noticed ...

**Comment by dmonad** [comment]
This is fixed in y-map@10.1.3 and y-array@10.1.4
