### ISSUE TITLE
Is it possible to set a specific property in an object?

### ISSUE THREAD

**Issue by r03ert0** [y-js/y-map#11]
I'm doing `y.share.map.set('one',{two:'three',four:'five'})`, which works ok.

How could I `y.share.map.get('one.two')?` or even `y.share.map.set('one.two','six')`? (these do not work)

**Comment by dmonad** [comment]
y-map does not make any assumption about your data in `map.set(name, data)`. Here are two methods to set a sub-property if data is an Object.

### Use Object.assign
```js
// set property `two` to `six`
map.set(name, Object.assign(map.get(name), { two: 'six' }))
```

### Use y-map
```js
// assuming map.get(name) is of type y-map
let myMap = map.set(name, Y.Map)

// set some propertyies
myMap.set('one', 'two')
myMap.set('three', 'four')
.. I think you get the idea..
```

**Comment by r03ert0** [comment]
thank you!
