### ISSUE TITLE
How to Delete a key locally?

### ISSUE THREAD

**Issue by harrshasri** [y-js/y-map#12]
When using IPFS I want to unsubscribe the topic and .delete(key)  locally. Not delete the key across the network.

How do I Achieve this?

**Comment by dmonad** [comment]
You could disconnect from the network and then delete the key. What is the problem here?

You can disconnect with `y.connector.disconnect()`. But I don't know if y-ipfs supports this (I'm not the author of the package)

**Comment by harrshasri** [comment]
There is no need to disconnect
 `.delete(key) ` Infact deletes just the local copy. I just tested.

Thanks, Anyways. :)
