### ISSUE TITLE
Detailed Error Info on Promises

### ISSUE THREAD

**Issue by Joeao** [y-js/y-map#2]
When getting a store that doesn't exist, the promise throws a console error.
Being told why the error occurred may be useful as it will help with scenarios such as `if doesn't exist, create`.

**Comment by Joeao** [comment]
To clarify: This can be reproduced by getting a map store on the client that hasn't been previously set.

**Comment by dmonad** [comment]
I implemented a method `.getType` - the counterpart of `.getPrimitive` (but always returns a promise). Please read the updated README for documentation.

Now you can just..

```
map.getType('nonExistingProperty')
  .then(function (val) {
    // this property exists
  }).catch(function () {
    // this property does not (yet) exist
  })
```

I think this is a usefull addition to Y.Type.
