### ISSUE TITLE
Document observer event

### ISSUE THREAD

**Issue by istvank** [y-js/y-map#5]
Hey, thanks for the great work! However, I cannot find in your documentation how the event looks like that the observer gets. E.g., it was hard work to figure out that I can get the value by event.object.get(event.name, ...). And after implementing it like this, I found it out the hard way that it also works with event.value. :dancer:

**Comment by dmonad** [comment]
Thanks for the note! :+1: I added some documentation

**Comment by istvank** [comment]
Cool! :+1:
