### ISSUE TITLE
event.value is undefined when you add a type to a YMap

### ISSUE THREAD

**Issue by lukebarlow** [y-js/y-map#6]
The event fired when you add a new key to a YMap has a value key when you add a primitive value, but has `undefined` value when you add a Y type. Here are two tests to illustrate. The first one passes and the second one fails. I'm not sure what the intended behaviour is, but maybe this is an issue which is easily fixed (In the event handler, I just do `event.value = event.object.get(event.name)`.

There's also a similar issue in YArray.toArray() where Y primitives appear as expected, but Y types show as undefined.

```
      it('event has correct value when setting a primitive on a YMap', async(function * (done) {
        var event
        yield flushAll()
        y1.observe(function (e) {
          event = e // just put it on event, should be thrown synchronously anyway
        })
        yield y1.set('stuff', 2)
        expect(event.value).toEqual(event.object.get(event.name))
        // delete
        y1.delete('stuff')
        done()
      }))
      it('event has correct value when setting a type on a YMap', async(function * (done) {
        var event
        yield flushAll()
        y1.observe(function (e) {
          event = e // just put it on event, should be thrown synchronously anyway
        })
        yield y1.set('stuff', Y.Map)
        expect(event.value).toEqual(event.object.get(event.name))
        // delete
        y1.delete('stuff')
        done()
      }))
```

**Comment by dmonad** [comment]
Thanks a lot for this! I integrated your tests in the test suite, and published fixed versions of y-array and y-map.
